---
platform: linux

image_resource:
  type: docker-image
  source: {repository: narwhalpivotal/base-image}

inputs:
  - name: repo

outputs:
  - name: artifacts

run:
  path: repo/ci_scripts/build.sh

params:
  TERM: -dumb
  GRADLE_OPTS: -Dorg.gradle.native=false

caches:
  - path: gradle
  - path: repo/client/node_modules