---
platform: linux

image_resource:
  type: docker-image
  source: {repository: jigsawdiux/ruby-golang-java-nodejs-chrome}

inputs:
  - name: repo

run:
  path: repo/ci_scripts/build.sh

params:
  TERM: -dumb
  GRADLE_OPTS: -Dorg.gradle.native=false

caches:
  - path: gradle
  - path: repo/client/node_modules