resources:
  - name: repo
    type: git
    source:
      uri: git@bitbucket.org:lovenirds/project_name.git
      branch: master
      private_key: {{bitbucket_ssh_key}}
      check_every: 20s

jobs:
- name: test
  plan:
  - get: repo
    trigger: true
  - task: client_test
    file: repo/ci_scripts/client_test.yml
  - task: server_test
    file: repo/ci_scripts/server_test.yml