resources:
  - name: repo
    type: git
    source:
      uri: git@gitlab.gs.mil:DCGS_Crew_Manager/narwhal.git
      branch: master
      private_key: {{gitlab_ssh_key}}
      check_every: 60s
  - name: prod
    type: cf
    source:
      api: {{cf_api}}
      username: {{cf_username}}
      password: {{cf_password}}
      organization: {{cf_organization}}
      space: {{cf_space}}

jobs:
- name: test
  plan:
  - get: repo
    trigger: true
  - task: test
    file: repo/ci_scripts/test.yml
- name: deploy
  plan:
  - get: repo
    trigger: true
    passed: [test]
  - task: build
    file: repo/ci_scripts/build.yml
  - put: prod
    params:
      manifest: artifacts/manifest.yml
