resources:
  - name: repo
    type: git
    source:
      uri: git@gitlab.gs.mil:DCGS_Crew_Manager/narwhal.git
      branch: master
      private_key: {{gitlab_ssh_key}}
      check_every: 120s

jobs:
- name: test
  plan:
  - get: repo
    trigger: true
  - task: client_test
    file: repo/ci_scripts/client_test.yml
  - task: server_test
    file: repo/ci_scripts/server_test.yml