resources:
  - name: repo
    type: git
    source:
      uri: git@bitbucket.org:lovenirds/narwhal.git
      branch: master
      private_key: {{gitlab_ssh_key}}
      check_every: 10s

jobs:
- name: unit-test
  plan:
  - get: repo
    trigger: true
  - aggregate:
    - task: client_test
      file: repo/ci_scripts/client_test.yml
    - task: server_test
      file: repo/ci_scripts/server_test.yml
- name: acceptance-test
  plan:
  - get: repo
    trigger: true
    passed: [unit-test]
  - task: acceptance_test
    privileged: true
    file: repo/ci_scripts/acceptance_test.yml