version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      NARWHAL_DB_URL: jdbc:postgresql://db:5432/narwhal-dev
      NARWHAL_DB_PASSWORD: narwhal
      NARWHAL_DB_USERNAME: narwhal
  db:
    image: "postgres:latest"
    environment:
      POSTGRES_PASSWORD: narwhal
      POSTGRES_USER: narwhal
      POSTGRES_DB: narwhal-dev
