version: '3'
services:
  db:
    image: "mysql:latest"
    environment:
      MYSQL_PASSWORD: narwhal
      MYSQL_USER: narwhal
      MYSQL_DATABASE: narwhaldev
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      NARWHAL_DB_URL: jdbc:mysql://db:3306/narwhaldev?useSSL=false
      NARWHAL_DB_PASSWORD: narwhal
      NARWHAL_DB_USERNAME: narwhal
    command: ./gradlew bootrun
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - app
    privileged: true
    environment:
      NARWHAL_APP_URL: http://app:8080
    command: ./ci_scripts/acceptance_test.sh
