spring:
  datasource:
    url: ${NARWHAL_DB_URL}
    username: ${NARWHAL_DB_USERNAME}
    password: ${NARWHAL_DB_PASSWORD}
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    deserialization:
      ACCEPT_EMPTY_STRING_AS_NULL_OBJECT: true
flyway:
  baseline-on-migrate: true
  baseline-version: 0
logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: debug
    org.springframework.ws: debug
    org.springframework.ws.client.MessageTracing: trace
    org.springframework.security: debug

security:
  user:
    name: tytus
    password: password
    role: USER