spring:
  datasource:
    url: ${NARWHAL_DB_URL}
    username: ${NARWHAL_DB_USERNAME}
    password: ${NARWHAL_DB_PASSWORD}
flyway:
  baseline-on-migrate: true
  baseline-version: 0
logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: debug